### ISSUE TITLE
Async does NOT work on latest WE version 7.2.6-beta-02 which supports 1.17.1

### ISSUE THREAD

**Issue by James-Cotterill** [SBPrime/AsyncWorldEdit#405]
Evening, 

Hope you are well? 

We have recently updated our server to 1.17.1 which required us to update WE to worldedit-bukkit-7.2.6-beta-02

This has however stopped async from starting:

[20:11:29 ERROR]: Could not load 'plugins\AsyncWorldEdit-3.9.1.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: java.lang.NoClassDefFoundError: Could not initialize class org.primesoft.asyncworldedit.utils.Reflection
        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:157) ~[patched_1.17.1.jar:git-Paper-154]
        at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:414) ~[patched_1.17.1.jar:git-Paper-154]
        at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:322) ~[patched_1.17.1.jar:git-Paper-154]
        at org.bukkit.craftbukkit.v1_17_R1.CraftServer.loadPlugins(CraftServer.java:404) ~[patched_1.17.1.jar:git-Paper-154]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:276) ~[patched_1.17.1.jar:git-Paper-154]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1126) ~[patched_1.17.1.jar:git-Paper-154]        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316) ~[patched_1.17.1.jar:git-Paper-154]
        at java.lang.Thread.run(Thread.java:831) [?:?]
Caused by: java.lang.NoClassDefFoundError: Could not initialize class org.primesoft.asyncworldedit.utils.Reflection
        at org.primesoft.asyncworldedit.utils.ClassLoaderHelper.setPlugin(ClassLoaderHelper.java:192) ~[AsyncWorldEdit-3.9.1.jar:?]
        at org.primesoft.asyncworldedit.utils.ClassLoaderHelper.cleanPlugin(ClassLoaderHelper.java:200) ~[AsyncWorldEdit-3.9.1.jar:?]
        at org.primesoft.asyncworldedit.AsyncWorldEditBukkit.<clinit>(AsyncWorldEditBukkit.java:99) ~[AsyncWorldEdit-3.9.1.jar:?]
        at java.lang.Class.forName0(Native Method) ~[?:?]
        at java.lang.Class.forName(Class.java:466) ~[?:?]
        at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:71) ~[patched_1.17.1.jar:git-Paper-154]
        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:153) ~[patched_1.17.1.jar:git-Paper-154]
        ... 7 more

Hopefully this is a quick and easy fix for you?

Thanks again for your great work and support

**Comment by SBPrime** [comment]
Hey,

I finished testing using the newest spigot (freshly compiled minutes ago ;) ), WE from dev bukkit on Minecraft 1.17.1. No issues plugin starts and works without any issues. What is your setup?

**Comment by James-Cotterill** [comment]
Good evening,

Thank you for prompt reply!

We actively update paper but our current version is : 

Paper 1.17.1 (#160) 

Async was working fine with an old version of WE but we had to update due to certain items like signs not pasting correctly. The version we are now using with the above error is:

WE version 7.2.6-beta-02 

If you need anymore details let me know.

Thank you

**Comment by SBPrime** [comment]
If that is the case I'll need the server startup log.

**Comment by James-Cotterill** [comment]
No worries.

This is the versions mentioned above on a test server and it seems to produce the same error:

https://pastebin.com/KEuWCMH7

Thanks again

**Comment by SBPrime** [comment]
There was an issue reported with with paper 154, I would suggest to try to updae to latest version.

**Comment by James-Cotterill** [comment]
Thank you for your response - updating Paper has worked!

Thank you so much for your continuous support.

Have a great day!
